apiVersion: v1
kind: Development
metadata:
  name: elasticsearch
spec:
  selectors:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      conatiners:
      - name: elasticsearch
        image: elasticsearch
        ports:
        - containerPort: 9200
      - name: kibana
        image: kibana
        ports:
        - containerPort: 5601
      - name: logstash
        image: logstash
        ports:
        - containerPort: 5044
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany:
  nfs:
    server: 10.0.0.21
    path: "/mnt/elk"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany:
  resources:
    requests:
      capacity: 2Gi
    
