apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany:
  nfs:
    server: 10.0.0.21
    path: "/mnt/elk"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany:
  resources:
    requests:
      capacity: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany:
  nfs:
    server: 10.0.0.21
    path: "/mnt/logstash"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany:
  resources:
    requests:
      capacity: 1Gi

---
apiVersion: apps/v1
kind: Development
metadata:
  name: elk
spec:
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      volumes:
      - name: elasticsearch-pvc
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
      volumes:
      - name: logstash-pvc
        persistentVolumeClaim:
          claimName: logstash-pvc
      conatiners:
      - name: elasticsearch
        image: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
          - name: elasticsearch-pvc
            path: /usr/share/elasticsearch/data
        volumeMounts:
        - name: logstash-pvc
          path: /usr/share/logstash/data
        env:
        - name: discovery.type
          value: single-node
      - name: kibana
        image: kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
      - name: logstash
        image: logstash
        ports:
        - containerPort: 5044
---
apiVersion: v1
kind: Service
metadata:
  name: elk-svc
spec:
  selector:
    app: elk
  ports: 
  - name: elk
    port: 80
    targetPort: 9200
    nodePort: 31111
  - name: elk-custom
    port: 8080
    targerPort: 9300
    NodePort: 31112
  type: NodePort


