apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  nfs:
    server: 10.0.0.21
    path: "/mnt/elasticsearch"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
<<<<<<< HEAD
      capacity: 1Gi

=======
      storage: 1Gi
>>>>>>> 3ecbec0c42a0858233a2fc1b678bb26da52348b6
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  nfs:
    server: 10.0.0.21
    path: "/mnt/logstash"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elk
spec:
  selector:
    matchLabels:
      app: elk
  template:
    metadata:
      labels:
        app: elk
    spec:
      volumes:
      - name: elasticsearch-pvc
        persistentVolumeClaim:
          claimName: elasticsearch-pvc
      - name: logstash-pvc
        persistentVolumeClaim:
          claimName: logstash-pvc
      containers:
      - name: elasticsearch
        image: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: single-node
        volumeMounts:
        - name: elasticsearch-pvc
          mountPath: /usr/share/elasticsearch/data
      - name: kibana
        image: kibana
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: http://localhost:9200
      - name: logstash
        image: logstash
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: logstash-pvc
          mountPath: /usr/share/logstash/config/logstash.conf
          subPath: logstash.conf

---
apiVersion: v1
kind: Service
metadata:
  name: elk-svc
spec:
  selector:
    app: elk
  ports: 
  - name: elasticsearch
    port: 9200
    targetPort: 9200
  - name: elasticsearch-custom
    port: 9300
    targetPort: 9300
  - name: kibana
    port: 5601
    targetPort: 5601
    nodePort: 31111
  type: NodePort


